name: Automated Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  cypress:
    name: E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core:
          - {name: 'WP trunk', version: 'https://wordpress.org/nightly-builds/wordpress-latest.zip'}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i && composer install --no-dev
    - name: Set the core version
      run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}
    - name: Set up WP environment
      run: npm run env:start
    - name: Setup pretty permalink
      run: npm run wp-env run tests-cli "wp rewrite structure '/%postname%/'"
    - name: Test
      run: npm run cypress:run
    - name: Store test screenshots
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: screenshots
        path: tests/cypress/screenshots
    - name: Store test videos
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: videos
        path: tests/cypress/videos
